# Use the official Node.js image
FROM node:20.16.0

# Create and change to the app directory
# WORKDIR /usr/src/app

# Copy application dependency manifests to the container image
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Expose the port the app runs on
EXPOSE 4001

# Run the application in development mode
CMD [ "npm", "run", "dev" ]